### ISSUE TITLE
Possible to upload .json or .vil as well?

### ISSUE THREAD

**Issue by mr-september** [Bastardkb/bastardkb-qmk#9]
Would it be possible/easy to also share those `.json` and/or `.vil` files, so that anyone still planning out a build can start customizing the firmware/layout, and maybe even design keycaps accordingly?

It doesn't look like QMK Configurator nor Vial supports just loading a .hex file, I think? 

(first custom keyboard ever, still completely new to everything.

**Comment by 0xcharly** [comment]
You should be able to build it yourself using the `qmk c2json` tool, _eg._:

```shell
qmk c2json -kb bastardkb/charybdis/3x5/v2/elitec -km default -o keymap.json keyboards/bastardkb/charybdis/3x5/keymaps/default/keymap.c
```

However, this might not work, since the QMK configurator tool will likely expect a format that matches the configuration in QMK upstream, which may not be up to date (we're upstreaming our changes, but reviews take time on the QMK side: https://github.com/qmk/qmk_firmware/pull/16778).

The `vial.json` files are available in the `vial` keymap for all boards on the `bkb-vial` branch.
